# Create a program that will play the “cows and bulls” game with the user. The game works like this:
# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the user 
# guessed correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in the wrong 
# place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user
# guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout the 
# game and tell the user at the end.

# made limit 20 guesses, if you don't get it right by then, you lose

# Say the number generated by the computer is 1038. An example interaction could look like this:
#  Welcome to the Cows and Bulls Game! 
#  Enter a number: 
#  >>> 1234
#  2 cows, 0 bulls
#  >>> 1256
#  1 cow, 1 bull
#  ...

def cowsNbulls():

    import random

    # Explanation
    print ("Hi there, welcome to Cows and Bulls.  For every digit that you guess correctly in the correct place, you get a “cow”.") 
    print ("For every digit you guess correctly in the wrong place, you get a 'bull'.")
    print ("You have 20 chances to get it right, otherwise, you lose!")
    print ("Enter 'exit' instead of a number guess if you want to quit early.")


    # creates the random 4 digit number, and returns a string of 4 numbers
    def random4digit():
        num = random.randint(1000,9999)
        num = str(num)
        return num

    # prompts user to guess, then compares it to the number determined by the random4digit function
    def cows_bulls(random4):
    
        user_guess = input("Guess a 4 digit number: ")
        user_guess = str(user_guess)

        if user_guess == "exit":
            return ("Ok, quitter.")

        else:
            i = 0
            cow = 0
            bull = 0

            for digit in user_guess:
                if digit == random4[i]:
                    cow = cow + 1
                    i = i + 1
                elif digit in random4:
                    bull = bull + 1
                    i = i + 1
                else: 
                    i = i + 1

            if cow == 4:
                return ("YOU WIN!!! Nice job!")
            else:
                hint = "number of cows: " + str(cow)+ " & number of bulls: " + str(bull)
                return hint


    # run the game using a for loop, with a limit of 20 tries
    # produce a random number
    game4digit = random4digit()
    print()
   
    for run in list(range(21)):
        answer = cows_bulls(game4digit)
        print (answer)
        print()
        if answer == "Ok, quitter.":
            break
        elif answer == "YOU WIN!!! Nice job!" :
            print ("Number of tries: " + str(run + 1))
            break
        else:
            pass

    print("The answer was " + str(game4digit))

### test function ###
cowsNbulls()

review = input("What did you think of the game? ")
